export const Products = [
  {
    nombre: 'Zapato azul',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/4SnyQps/1.jpg',
  },
  {
    nombre: 'Zapato rojo',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/d2cd0wB/2.jpg',
  },
  {
    nombre: 'Zapato verde',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/mNDBVL6/3.jpg',
  },
  {
    nombre: 'Zapato gris',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/xS0m3FC/4.jpg',
  },
  {
    nombre: 'Zapato cafe',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/Wt8Ch4R/5.jpg',
  },
  {
    nombre: 'Zapato miel',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/mbRcrDz/6.jpg',
  },
  {
    nombre: 'Zapato aguamarina',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/cbF1zDs/7.jpg',
  },
  {
    nombre: 'Zapato piel',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/pLv45RC/9.jpg',
  },
  {
    nombre: 'Zapato perla',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/0QJQKb4/10.jpg',
  },
  {
    nombre: 'Zapato marinado',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/FHy7QDZ/11.jpg',
  },
  {
    nombre: 'Zapato azul1',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/4sYy8hZ/12.jpg',
  },
  {
    nombre: 'Zapato azul2',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/YLWzrvq/14.jpg',
  },
  {
    nombre: 'Zapato azul3',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/cxtsMVJ/15.jpg',
  },
  {
    nombre: 'Zapato azul4',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/tbk5kHt/16.jpg',
  },
  {
    nombre: 'Zapato azul5',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/KLWXJ5s/17.jpg',
  },
  {
    nombre: 'Zapato azul6',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/8BCDZrr/18.jpg',
  },
  {
    nombre: 'Zapato azul7',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/19dgKNd/19.jpg',
  },
  {
    nombre: 'Zapato azul8',
    precio: 5000,
    referencia: 'G40',
    foto: 'https://i.ibb.co/h1CQ9wh/20.jpg',
  },
];
